spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.zhang.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改eureka上默认的描述信息
    prefer-ip-address: true #为true返回服务的ip地址

#info配置
info:
  app.name: zhang
  company.name: Hello World Normal
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.zhang.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改eureka上默认的描述信息
    prefer-ip-address: true #为true返回服务的ip地址

#info配置
info:
  app.name: zhang
  company.name: Hello World Normal